#ifndef UNITTESTBOT_COPYRIGHT_H
#define UNITTESTBOT_COPYRIGHT_H

#include <string>
#include "config.h"

namespace Copyright {
    static inline const std::string GENERATED_C_CPP_FILE_HEADER =
        "/*\n"
        " * This file is automatically generated by UnitTestBot. "
        "For further information see "
        PROJECT_HOMEPAGE_URL
        "\n */\n";

    static inline const std::string GENERATED_MAKEFILE_HEADER =
        "# This file is automatically generated by UnitTestBot. "
        "For further information see "
        PROJECT_HOMEPAGE_URL
        "\n";

    static inline const std::string GENERATED_CMAKELISTS_FILE_HEADER =
            "#[[\n"
            "This file is automatically generated by UnitTestBot. "
            "For further information see "
            PROJECT_HOMEPAGE_URL
            "\n ]]\n";

    static inline const std::string GENERATED_SH_HEADER = GENERATED_MAKEFILE_HEADER;
};


#endif // UNITTESTBOT_COPYRIGHT_H
