/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2012-2021. All rights reserved.
 */

#ifndef UNITTESTBOT_COPYRIGHT_H
#define UNITTESTBOT_COPYRIGHT_H

#include <string>

namespace Copyright {
    static inline const std::string GENERATED_C_CPP_FILE_HEADER =
        "/*\n"
        " * This file is automatically generated by UnitTestBot. "
        "For further information see https://github.com/UnitTestBot/UTBotCpp\n"
        " * Copyright (c) Huawei Technologies Co., Ltd. 2012-2021. All rights reserved.\n"
        " */\n";

    static inline const std::string GENERATED_MAKEFILE_HEADER =
        "# This file is automatically generated by UnitTestBot. "
        "For further information see https://github.com/UnitTestBot/UTBotCpp\n"
        "# Copyright (c) Huawei Technologies Co., Ltd. 2012-2021. All rights reserved.\n";

    static inline const std::string GENERATED_SH_HEADER = GENERATED_MAKEFILE_HEADER;
};


#endif // UNITTESTBOT_COPYRIGHT_H
