#include <signal.h>

#define RAISE_FUNC_DEF(i)      \
    int raise_func##i(int x) { \
        return raise(i);       \
    }

RAISE_FUNC_DEF(0)
RAISE_FUNC_DEF(1)
RAISE_FUNC_DEF(2)
RAISE_FUNC_DEF(3)
RAISE_FUNC_DEF(4)
RAISE_FUNC_DEF(5)
RAISE_FUNC_DEF(6)
RAISE_FUNC_DEF(7)
RAISE_FUNC_DEF(8)
RAISE_FUNC_DEF(9)
RAISE_FUNC_DEF(10)
RAISE_FUNC_DEF(11)
RAISE_FUNC_DEF(12)
RAISE_FUNC_DEF(13)
RAISE_FUNC_DEF(14)
RAISE_FUNC_DEF(15)
RAISE_FUNC_DEF(16)
RAISE_FUNC_DEF(17)
RAISE_FUNC_DEF(18)
RAISE_FUNC_DEF(19)
RAISE_FUNC_DEF(20)
RAISE_FUNC_DEF(21)
RAISE_FUNC_DEF(22)
RAISE_FUNC_DEF(23)
RAISE_FUNC_DEF(24)
RAISE_FUNC_DEF(25)
RAISE_FUNC_DEF(26)
RAISE_FUNC_DEF(27)
RAISE_FUNC_DEF(28)
RAISE_FUNC_DEF(29)
RAISE_FUNC_DEF(30)
RAISE_FUNC_DEF(31)

void raise_stop(int x) {
    raise(SIGSTOP);
    raise(SIGSTOP);
    raise(SIGSTOP);
}
